eukaryotes:
  database: pathogen_euk_track
  host:     web-mii-shap
  port:     3303
  user:     pathpipe_ro
  #password: 

prokaryotes:
  database: pathogen_prok_track
  host:     web-mii-shap
  port:     3303
  user:     pathpipe_ro

helminths:
  database: pathogen_helminth_track
  host:     web-mii-shap
  port:     3303
  user:     pathpipe_ro

viruses:
  database: pathogen_virus_track
  host:     web-mii-shap
  port:     3303
  user:     pathpipe_ro

metahit:
  database: pathogen_metahit_track
  host:     web-mii-shap
  port:     3303
  user:     pathpipe_ro
